### ISSUE TITLE
document index command raises TypeError

### ISSUE THREAD

**Issue by anthony-affinda** [Codoc-os/django-opensearch-dsl#41]
Running `./manage.py opensearch document index` returns this stacktrace:

```
Traceback (most recent call last):
  File "./manage.py", line 56, in <module>
    run(sys.argv)
  File "./manage.py", line 52, in run
    execute_from_command_line(argv)
  File "/home/anthony/.pyenv/versions/apps/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/anthony/.pyenv/versions/apps/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/anthony/.pyenv/versions/apps/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/anthony/.pyenv/versions/apps/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/anthony/.pyenv/versions/apps/lib/python3.8/site-packages/django_opensearch_dsl/management/commands/opensearch.py", line 356, in handle
    options["func"](**options)
  File "/home/anthony/.pyenv/versions/apps/lib/python3.8/site-packages/django_opensearch_dsl/management/commands/opensearch.py", line 182, in _manage_document
    qs = document.get_queryset(filter_=filter_, exclude=exclude_, count=count).count()
TypeError: get_queryset() got an unexpected keyword argument 'filter_'
```

Relevant packages:
```
django-opensearch-dsl==0.5.1
opensearch-py==2.2.0
```

I have a very basic OS Document Class:

```
from opensearchpy import Float
from django_opensearch_dsl import Document as OSDocument
from django_opensearch_dsl import fields
from django_opensearch_dsl.registries import registry as opensearch_registry


class DenseVector(Float):
    name = "knn_vector"

    def __init__(self, dims=6, **kwargs):
        kwargs["multi"] = True
        kwargs["dimension"] = dims
        super(DenseVector, self).__init__(**kwargs)


class DenseVectorField(fields.DODField, DenseVector):
    pass


@opensearch_registry.register_document
class FingerPrintDocument(OSDocument):
    fingerprint = DenseVectorField(attr="fingerprint")
    collection = fields.IntegerField(attr="collection_id")

    class Index:
        name = "fingerprint"
        settings = {
            "number_of_shards": 1,
            "number_of_replicas": 0,
            "index": {"knn": True, "knn.algo_param.ef_search": 100},
        }

    class Django:
        model = <my django model>
```

**Comment by qcoumes** [comment]
Did you override the `get_queryset()` method in one of your `Document` classes? If so did use the same prototype (i.e. `def get_queryset(self, filter_=None, exclude=None, count=None)`)

**Comment by anthony-affinda** [comment]
I actually did override it and didn't use the correct prototype, looks good now! It was an oversight from my end since I was previously using the elasticsearch django dsl
